### ISSUE TITLE
How can I  get the output after inference ?

### ISSUE THREAD

**Issue by leo851001** [openvinotoolkit/dlstreamer_gst#118]
Hi,

I have install the "dlstreamer_gst" with docker container in Ubuntu18.04,
My work is to do some inference and record the performance,
At the first I used the sample code : 
`gst-launch-1.0 filesrc location=cut.mp4 ! decodebin ! videoconvert ! gvadetect model=face-detection-adas-0001.xml ! gvaclassify model=emotions-recognition-retail-0003.xml model-proc=emotions-recognition-retail-0003.json ! gvawatermark ! xvimagesink sync=false`
**Q1** : Then I get the error with : xvimagesink0: Could not initialise Xv output & No Xv Port available
After a lot of try , I give up for using x-window (lol)

I try to save the output video after inference , use the code like : 
`gst-launch-1.0 filesrc location=/root/video-examples/test.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=/root/intel_models/person-detection-retail-0013.xml device=CPU ! queue ! gvawatermark ! videoconvert ! x264enc ! h264parse ! mp4mux ! filesink location=/root/video-examples/video.mp4`
I successfully got the result video with bounding box,
BUT !! Just only have the bounding box,
**Q2** :  I need the others information like "fps"、"confidence" ..... How can I get it ?

I have try the "fpsdisplaysink" but it seem like didn't support saving output to the file ... filesink(?)
**Q3** :  If it's ok , how to use it ?

**Q4** : I don’t really need to get the video, the result can also be displayed in cmd line, is there any way can do it ?

Please excuse my poor English.

Thanks all,
Leo

**Comment by mliu2020** [comment]
Hi Leo,

Q1: I think you might not enable the rendering in the docker command, if you run the docker image from [OpenVINO Docker Hub](https://hub.docker.com/r/openvino/ubuntu18_data_dev), you can try this command: 
`xhost local:root && docker run -it \
>     --device /dev/dri:/dev/dri \
>     --device-cgroup-rule='c 189:* rmw' \
>     -v ~/.Xauthority:/root/.Xauthority \
>     -v /tmp/.X11-unix/:/tmp/.X11-unix/ \
>     -e DISPLAY=$DISPLAY \
>     -v /dev/bus/usb:/dev/bus/usb \
> --rm openvino/ubuntu18_data_dev:latest /bin/bash`
Q2:  I am assuming you are in the rendering case but not file output. You can add element 'gvafpscount' after gvadetect element to show the FPS number. For example, 
`gst-launch-1.0 filesrc location=/root/video-examples/test.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=/root/intel_models/person-detection-retail-0013.xml device=CPU ! queue ! gvawatermark ! gvafpscount ! videoconvert ! x264enc ! h264parse ! mp4mux ! filesink location=/root/video-examples/video.mp4`
But gvafpscount only add an overlay to the final display, it can't be used if you want to put the fps number at the output frame.
Q3: 'fpsdisplaysink' can't be used to output to filesink because it doesn't have [src pad](https://gstreamer.freedesktop.org/documentation/application-development/basics/elements.html?gi-language=c#source-elements).
Q4: You can refer to our [c++ sample](https://github.com/openvinotoolkit/dlstreamer_gst/tree/master/samples/cpp/draw_face_attributes) or [python sample](https://github.com/openvinotoolkit/dlstreamer_gst/tree/master/samples/python/draw_face_attributes) to replace the draw output with a printf if you only need to print the result in the terminal.

Mark

**Comment by leo851001** [comment]
@mliu2020 
Very grateful for your help, gvafpscount <- This method can achieve my goal !!
Please allow me to ask another question...
How can I convert my model FP32/FP16 to INT8 ?
Is there only one way by using DL Workbench ?
Can't I use the INT8 model  just like I use FP32/FP16 ?

Thank you very much,
Leo

**Comment by mliu2020** [comment]
Hi @leo851001 

Yes, you can use DL Workbench to convert to INT8 and use it in the sample code the same way as FP32 model file.

Let me know if you have issues.

Mark

**Comment by leo851001** [comment]
@mliu2020 
I used the DL application and I get the result : 
![image](https://user-images.githubusercontent.com/30343874/94326564-47731f80-ffd7-11ea-9be8-ed1dc6647bfd.png)
This works normally on DL, FPS increased more than twice !!

I downloaded the successfully converted model ( ssd_mobilenet_v1_coco_- INT8.tar.gz )
In this file have [ ssd_mobilenet_v1_coco_- INT8.xml ] and [ ssd_mobilenet_v1_coco_- INT8.bin ]
I run the pipeline with these two files, then I get the error : 
![image](https://user-images.githubusercontent.com/30343874/94326822-5f4ba300-ffd9-11ea-82d8-ab537d8f6f19.png)

My pipeline is : 
`gst-launch-1.0 -v  filesrc location=./video-examples/test.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=./intel_models/ssd_mobilenet_v1_coco_2018_01_28/INT8/frozen_inference_graph_int8.xml device=CPU ! queue ! gvafpscounter ! fakesink`

What problem did i get ?
so sad :(

Leo

**Comment by leo851001** [comment]
Update , Problem has been solved : )

**Comment by brmarkus** [comment]
You wrote "ssd_mobilenet_v1_coco_- INT8.xml" and "ssd_mobilenet_v1_coco_- INT8.bin", but in the pipeline you use "ssd_mobilenet_v1_coco_int8.bin", so a different spelling?

**Comment by varunjain3** [comment]
> Q1: I think you might not enable the rendering in the docker command, if you run the docker image from [OpenVINO Docker Hub](https://hub.docker.com/r/openvino/ubuntu18_data_dev), you can try this command:
> 
> `xhost local:root && docker run -it --device /dev/dri:/dev/dri --device-cgroup-rule='c 189:* rmw' -v ~/.Xauthority:/root/.Xauthority -v /tmp/.X11-unix/:/tmp/.X11-unix/ -e DISPLAY=$DISPLAY -v /dev/bus/usb:/dev/bus/usb --rm openvino/ubuntu18_data_dev:latest /bin/bash`

Hi @mliu2020 Mark,
I was using the same command to start the container, but I m not sure how docker works properly. I want a workflow like a VM wherein I can edit some things get results exit out of the container analyse do some changes and get more analytics. 

But running this docker command, I realised my data is lost always. I tried making a commit copy of the same, but every time I start that docker container using ```docker start <containername>``` and ```docker attach <containername>```, but I am not able to connect the display and thus getting the xvimagesink error. 

I tried manually saving the video but I'm again encountering an error where it says
```
erroneous pipeline: no element "x264enc"
```

**Comment by mliu2020** [comment]
Hi @varunjain3,

Sorry for the late response.

Did you already solve this problem? If not, I have created issue #173 to answer your question. Let's discuss there.

Mark
