### ISSUE TITLE
How can I use Yolov5 model ? 

### ISSUE THREAD

**Issue by uyuta** [openvinotoolkit/dlstreamer_gst#122]
I want to use yolov5 model.
so , i convert yolov5 model to openvino model  with reference to the following,
https://github.com/ultralytics/yolov5/issues/891
How can I use this with dlstreamer?

Thanks.

**Comment by mliu2020** [comment]
Hi @uyuta,

Yes, you can use it as long as you convert it to Intel’s format. But you should use gvainference with customized pre/post processing.

You can follow the examples to construct your project:

- At "master" branch, refer to either [python sample](https://github.com/openvinotoolkit/dlstreamer_gst/tree/master/samples/python/draw_face_attributes) or [cpp sample](https://github.com/openvinotoolkit/dlstreamer_gst/tree/master/samples/cpp/draw_face_attributes); then replace "gvadetect" element with "gvainference" element.
- At "preview/python_yolov3-support" branch, refer to ["postproc-callback" example](https://github.com/openvinotoolkit/dlstreamer_gst/blob/preview/python_api-yolov3_support/samples/python/postproc_callbacks/postproc_callbacks.py).

Let me know if you have more questions.

Mark

**Comment by uyuta** [comment]
Hi,
Thank you for your help.
I'll give it a try.

**Comment by mliu2020** [comment]
Hi @uyuta,

The sample in the preview/python_yolov3-support was obsoleted, For gvainference example, you can also check [this simple example](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/samples/gst_launch/gvapython/face_detection_and_classification/face_detection_and_classification.sh) in our current release.

Mark

**Comment by mliu2020** [comment]
Hi @uyuta,

Did you try your code with the example code?

Let me know if you need help.

Mark

**Comment by mliu2020** [comment]
Hi @uyuta,

Have you try my suggestions or if you have more question?

I will close this issue if no question for 7 days.

Mark

**Comment by varunjain3** [comment]
> I want to use yolov5 model.
> so , i convert yolov5 model to openvino model with reference to the following,
> [ultralytics/yolov5#891](https://github.com/ultralytics/yolov5/issues/891)
> How can I use this with dlstreamer?
> 
> Thanks.

Hi @uyuta, Were you able to get the yolov5 running with dl streamer? Could you share the steps?

Hi @mliu2020, does dl streamer support sequential gva-inference/detect calls? I was wondering if I could do something like this [example](https://github.com/intel-iot-devkit/safety-gear-detector-python) from the iot kit but with dl streamer

**Comment by mliu2020** [comment]
@varunjain3,

Sorry for the late response, somehow this post was ignored.

Yes, I checked your example, it has a detection followed by inference operations with multiple ROI input. With our recently release 2021.2. You can use gvadetect + gvainference to implement this example. We added a new feature called roi-list to gvainference so it can process multiple ROI input.

To use this feature, use the argument "inference-region=roi-list" so the gvainference will pick up the roi as input instead of "full-frame", you can refer to the example below:
https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/samples/python/draw_face_attributes/draw_face_attributes.py#L90

Let me know if this can solve your question.

@uyuta, do you have more question on Yolo5? I want to close this issue if no more questions.

Mark Liu

**Comment by mliu2020** [comment]
@uyuta,

I have confirmed DL Streamer doesn't support Yolo5 yet.

Please following our new releases and check we have an update on the Yolo5 support.

Mark Liu
