### ISSUE TITLE
how to use driver-action-recognition model from gva gstreamer pipeline?

### ISSUE THREAD

**Issue by wfchair** [openvinotoolkit/dlstreamer_gst#128]
driver-action-recognition-adas-0002 model has driver-action-recognition-adas-0002-encoder and driver-action-recognition-adas-0002-decoder. I don't know how to use the model from  gva gstreamer pipeline.

Would anyone be kind to give a simple gva gstreamer pipeline example like the following vehicle-license-plate-detection example?

gst-launch-1.0 v4l2src ! decodebin ! video/x-raw ! videoconvert ! gvadetect model=~/intel/dl_streamer/models/intel/vehicle-license-plate-detection-barrier-0106/FP32/vehicle-license-plate-detection-barrier-0106.xml model-proc=vehicle-license-plate-detection-barrier-0106.json ! queue ! gvaclassify model=~/intel/dl_streamer/models/intel/license-plate-recognition-barrier-0001/FP32/license-plate-recognition-barrier-0001.xml model-proc=license-plate-recognition-barrier-0001.json device=CPU object-class=license-plate ! queue ! gvawatermark ! fpsdisplaysink video-sink=xvimagesink sync=false

**Comment by mliu2020** [comment]
@wfchair,

Sorry for the late response, this seems slip away from our attention.

I checked his use case again and the model driver-action-recognition comes as a pair, I am not sure how to use it so I have following suggestions:

- You have to do some research on how to use it in openVINO application. What is the processing order from inference point of view? 
- Then you can go to [custom processing](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Custom-Processing) page and raise question after reading it.

Let us know if you have specific questions during these steps.

Mark

**Comment by mliu2020** [comment]
Hi @wfchair,

Not sure if you have investigated my suggestions.

With our recently release 2021.2, I have some update to your request. You can use gvadetect + gvainference to implement this pipeline. We added a new feature ROI list to gvainference so it can process multiple ROI output from gvadetect.

To use this feature, use the argument "inference-region=roi-list" so the gvainference will pick up the roi as input instead of "full-frame", you can refer to the example below:
https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/samples/python/draw_face_attributes/draw_face_attributes.py#L90

Let me know if this can solve your issue.

Mark Liu

**Comment by mliu2020** [comment]
@wfchair,

Thanks so much for using our product. Since I don't receive your reply, I assume it is either resolved or no interested any more. Let me close this issue for now.

Feel free to re-open it, or it is better to open an new issue against our new release.

Mark Liu
