### ISSUE TITLE
Build Dl-Streamer in WSL-Ubuntu

### ISSUE THREAD

**Issue by Rasmita-Ardu** [openvinotoolkit/dlstreamer_gst#223]
Hi, 
      In order to use MQTT method in gvametapublish which doesn't have Windows support ( [issue](https://github.com/openvinotoolkit/dlstreamer_gst/issues/219)
     Thus, I am trying to build Dl-Streamer in WSL 2 - Ubuntu. 
I followed the [install guide](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Install-Guide) : Option #3: Compile DL Streamer from sources on host system
I ran the following commands :
`cd /opt/intel/openvino_2021/install_dependencies/
sudo -E ./install_NEO_OCL_driver.sh`

Output : 
![image](https://user-images.githubusercontent.com/34830728/127157635-3c9d5c0b-d983-43ae-8aad-a1609946fed7.png)

`cd ~/intel/dlstreamer_gst/scripts
./install_dependencies.sh`

Output :
![image](https://user-images.githubusercontent.com/34830728/127158562-1d1c6f86-5bcf-4a2f-aad6-6fa677137947.png)
![image](https://user-images.githubusercontent.com/34830728/127158643-85fd56e1-2b35-4026-a6d0-182228454090.png)

I restarted my laptop, still clinfo is 0
![image](https://user-images.githubusercontent.com/34830728/127158845-b880ed71-e33f-4ec6-b25c-3cf3bb87a90b.png)

Can anyone tell where am I going wrong ?

**Comment by mliu2020** [comment]
Hi @Rasmita-Ardu,

Thanks for all the trail and screen capture. 

I never heard OpenCL is supported in WSL 2, I searched around and found [Microsoft GPU support announcement last year](https://ubuntu.com/blog/new-gpu-and-gui-features-announced-for-wsl-at-build). But this didn't clarify OpenCL support in WSL, then I found these posts: [6951](https://github.com/microsoft/WSL/issues/6951), [6372](https://github.com/microsoft/WSL/issues/6372), [6539](https://github.com/microsoft/WSL/issues/6539). It seems this issue is unsolved yet.

I will double check with dev team to confirm.

Mark

**Comment by mliu2020** [comment]
Hi @Rasmita-Ardu,

Is it OK to close this issue? Let me know you still have questions.

Mark
